name: Check Linting and Formatting

on: [ push, pull_request ]

jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: "Ruff Lint Check"
            uses: astral-sh/ruff-action@v1
            continue-on-error: true
          - name: "Ruff Format Check"
            uses: astral-sh/ruff-action@v1
            with:
              args: "format --diff"
